
name: CI
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt
      - name: Run Bandit (Python code checker)
        run: bandit -r . -f xml -o flaskapp_faraday_bandit.xml || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v2
        with:
          name: bandit-report
          path: flaskapp_faraday_bandit.xml


  upload:
    if: ${{ always() }}
    needs: [build]

    runs-on: ubuntu-latest

    container:
      image: python:3.9.1
      options: --user root -v ${{ github.workspace }}:/reports/:rw

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Download Bandit Report Artifact
      uses: actions/download-artifact@master
      with:
        name: bandit-report
        path: bandit-report


#     Faraday CLI approach
    - name: Upload Reports to Faraday
      run: |
        pip install faraday-cli
        faraday-cli auth -f ${{ secrets.FARADAY_HOST }} -u ${{ secrets.FARADAY_USERNAME }} -p ${{ secrets.FARADAY_PASSWORD }}
        faraday-cli tool report -w ${{ secrets.FARADAY_WORKSPACE }} /reports/bandit-report/flaskapp_faraday_bandit.xml
        faraday-cli tool report -w ${{ secrets.FARADAY_WORKSPACE }} --tag-vuln ${{ github.event.repository.name }} /reports/zap-report/zap-report.xml


